DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS expense;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  occupation TEXT NOT NULL,
  age INTEGER NOT NULL,
  income INTEGER NOT NULL




);

CREATE TABLE expense (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  cost INTEGER NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);